import Head from 'next/head';
import Link from 'next/link';
import { useCurrentUser } from '../src/hooks/auth/useCurrentUser';
import { NextPage } from 'next';
import { withLayout } from '@/layout/Layout';

const Home: NextPage = () => {
  const { user: currentUser } = useCurrentUser();
  return (
    <div className="">
      <Head>
        <title>NextJS JWT Auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <p className="">{currentUser ? `Hello` : 'You are not logged in !'}</p>
        <div className="">
          <Link href="/about" className="">
            <h2>About Page &rarr;</h2>
            <p>This is a public route for every user!</p>
          </Link>

          <Link href="/login" className="">
            <h2>Login Page &rarr;</h2>
            <p>This is a private route for unauthenticated user!</p>
          </Link>

          <Link href="/taskmanager" className="">
            <h2>Taskmanager Page &rarr;</h2>
            <p>This is a private route for authenticated user!</p>
          </Link>
        </div>
      </main>
    </div>
  );
};

export default withLayout(Home);
