import Head from 'next/head';
import { useCurrentUser } from '../src/hooks/auth/useCurrentUser';
import { NextPage } from 'next';
import { withLayout } from '@/layout/Layout';

const Home: NextPage = () => {
  const { user: currentUser } = useCurrentUser();
  return (
    <div className="">
      <Head>
        <title>Taskmanager Next JS Nest JS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <p className="">{currentUser ? `Hello` : 'You are not logged in !'}</p>
      </main>
    </div>
  );
};

export default withLayout(Home);
